apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis06
  labels:
    name: redis06
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
#  claimRef:
#    namespace: default
#    name: redis06-pvc
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /redis06
