apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis05
  labels:
    name: redis05
spec:
#  storageClassName: manual
#  persistentVolumeReclaimPolicy: Retain
#  claimRef:
#    namespace: default
#    name: redis05-pvc
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /redis05
