apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis01
  labels:
    name: redis01
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
#  claimRef:
#    namespace: default
#    name: redis01-pvc
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /redis01
