apiVersion: v1
kind: redis-cluster-service
metadata:
  name: redis-cluster-service
  labels:
    name: redis-cluster-service
spec:
  ports:
  - port: 6379
    name: client
  - name: gossip
    port: 16379
  - name: client
    targetPort: 6379
  - name: gossip
    targetPort: 16379
#  clusterIP: None
  selector:
    name: redis