apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis04
  labels:
    name: redis04
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
#  claimRef:
#    namespace: default
#    name: redis04-pvc
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /redis04
