apiVersion: v1
kind: Service
metadata:
  namespace: development
  name: jekyll
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 4000
#    name: http
    protocol: TCP
    nodePort: 30097
  selector:
    run: jekyll
