kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: development
  name: jekyll-site
  labels:
    name: jekyll-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  