apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-mysql-pv
spec:
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: default
    name: drupal-mysql-pvc
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /drupal-mysql-data
