apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
  labels:
    name: data-pv
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
#  claimRef:
#    namespace: default
#    name: data-pvc
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /web
