kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-pvc
  labels:
    name: data-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  