apiVersion: v1
kind: Service
metadata:
  name: gop-fs-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
#    name: http
    protocol: TCP
    nodePort: 31200
  selector:
    name: gop-file-server
