apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vote
  name: db-deployment
  labels:
    name: db-deployment
spec:
  selector:
    matchLabels:
      name: db-deployment
  template:
    metadata:
      name: db-deployment
      labels:
        name: db-deployment
    spec:
      containers:
      - name: db-deployment
        image: postgres:9.4
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      volumes:
      - name: db-data
        emptyDir: {}
