apiVersion: v1
kind: Service
metadata:
  namespace: vote
  name: db
spec:
#  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
#    name: http
    protocol: TCP
#    nodePort: 31000
  selector:
    name: db-deployment
