apiVersion: v1
kind: Service
metadata:
  namespace: vote
  name: redis
#  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
#    name: http
    protocol: TCP
#    nodePort: 31000
  selector:
    name: redis-deployment
