apiVersion: v1
kind: Service
metadata:
  namespace: vote
  name: result-service
  type: NodePort
  ports:
  - port: 5001
    targetPort: 80
#    name: http
    protocol: TCP
    nodePort: 31001
  selector:
    name: result-deployment
