apiVersion: v1
kind: Service
metadata:
  namespace: vote
  name: vote-service
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 80
#    name: http
    protocol: TCP
    nodePort: 31000
  selector:
    name: vote-deployment
